<?php

use App\Landlord;
use Illuminate\Database\Seeder;

class LandlordsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      // $Landlord = new Landlord;
      // $Landlord->delete();
      DB::table('landlords')->delete();

      $Landlord = new Landlord();
      $Landlord->title = "Chief";
      $Landlord->name = "OYO STATE SMALL SCALE INDUSTRIES COMPLEX, IYAGANKU, IBADAN.";
      $Landlord->phone = "08034028415";
      $Landlord->email = "null";
      $Landlord->address_office = "IYAGANKU";
      $Landlord->address_residence = "IYAGANKU";
      $Landlord->bank_name = "ECO BANK NIG. PLC";
      $Landlord->account_name = "OYO STATE SMALL SCALE INDUSTRY COMPLEX";
      $Landlord->account_no = "2282053489";
      $Landlord->branch = "NEW COURT ROAD";
      $Landlord->kin_name = "HON MUFUTAU  SALAWU   DEPUTY GOVERNOR IYIOLA OLADOKUN";
      $Landlord->kin_phone = "08023253814";
      $Landlord->kin_address = "BASHORUN";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Barr";
      $Landlord->name = "Kayode Olatunji";
      $Landlord->phone = "08033592396";
      $Landlord->email = "null";
      $Landlord->address_office = "37, Muritala Muhammed way, Kano";
      $Landlord->address_residence = "Felele Area, Ibadan";
      $Landlord->bank_name = "Union Bank";
      $Landlord->account_name = "Kayode Olatunji & Co";
      $Landlord->account_no = "0021746586";
      $Landlord->branch = "Lagos";
      $Landlord->kin_name = "Mrs. Olatunji";
      $Landlord->kin_phone = "null";
      $Landlord->kin_address = "37, Muritala Muhammed way, Kano";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaji";
      $Landlord->name = "Aderemi Olofa (Ogunpa Shopping Complex)";
      $Landlord->phone = "08023517336";
      $Landlord->email = "remi.olofa@remiolofa.com";
      $Landlord->address_office = "29, Lebanon Street, Old Gbagi, Ibadan";
      $Landlord->address_residence = "Remi Olofa Estate, Akuru Area, Ibadan";
      $Landlord->bank_name = "First City Monument Bank";
      $Landlord->account_name = "Alhaji Aderemi Olofa";
      $Landlord->account_no = "0649432018";
      $Landlord->branch = "Lebanon Street, Gbagi, Ibadan";
      $Landlord->kin_name = "Alhaja Kudirat Adenike Olofa";
      $Landlord->kin_phone = "08077747815";
      $Landlord->kin_address = "Remi Olofa Estate, Akuru Area, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaji";
      $Landlord->name = "Ibrahim Oyeleye";
      $Landlord->phone = "08033575556";
      $Landlord->email = "null";
      $Landlord->address_office = "New Gbagi Market";
      $Landlord->address_residence = "No 2, Road 219 Ilupeju Estate, Bodija";
      $Landlord->bank_name = "First Bank";
      $Landlord->account_name = "Mrs. Oluwatoyin Ibrahim";
      $Landlord->account_no = "3048985247";
      $Landlord->branch = "Ibadan";
      $Landlord->kin_name = "Biola Adedoja";
      $Landlord->kin_phone = "null";
      $Landlord->kin_address = "Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mrs";
      $Landlord->name = "Modupe Okoaye";
      $Landlord->phone = "08077296398";
      $Landlord->email = "null";
      $Landlord->address_office = "Lagos";
      $Landlord->address_residence = "Lagos";
      $Landlord->bank_name = "null";
      $Landlord->account_name = "null";
      $Landlord->account_no = "null";
      $Landlord->branch = "null";
      $Landlord->kin_name = "null";
      $Landlord->kin_phone = "08077296398";
      $Landlord->kin_address = "Lagos";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mr";
      $Landlord->name = "Akorede Adisa";
      $Landlord->phone = "08070801171";
      $Landlord->email = "null";
      $Landlord->address_office = "4th Floor Providence Court, Coca cola, Ibadan";
      $Landlord->address_residence = "Oke Ado";
      $Landlord->bank_name = "First Bank Plc";
      $Landlord->account_name = "Adisa Akorede Kamoru";
      $Landlord->account_no = "3002267693";
      $Landlord->branch = "Dugbe";
      $Landlord->kin_name = "Nike Adisa";
      $Landlord->kin_phone = "08090801171";
      $Landlord->kin_address = "4th Floor Providence Court, Coca cola, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mr";
      $Landlord->name = "A. O Aderinokun";
      $Landlord->phone = "08033446220";
      $Landlord->email = "null";
      $Landlord->address_office = "Oke Itunu Area, Mokola, Ibadan";
      $Landlord->address_residence = "Oke Itunu Area, Mokola, Ibadan";
      $Landlord->bank_name = "Stanbic Bank Plc";
      $Landlord->account_name = "O. A . Aderionkun";
      $Landlord->account_no = "0005933960";
      $Landlord->branch = "Lebanon";
      $Landlord->kin_name = "Mrs. Aderiokun";
      $Landlord->kin_phone = "09090475919";
      $Landlord->kin_address = "Oke Itunu Area, Mokola, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mr";
      $Landlord->name = "Remi Adedeji";
      $Landlord->phone = "08056526423";
      $Landlord->email = "null";
      $Landlord->address_office = "Felele Express";
      $Landlord->address_residence = "Felele Area, Ibadan";
      $Landlord->bank_name = "GTB";
      $Landlord->account_name = "Remi Adedeji";
      $Landlord->account_no = "0030302067";
      $Landlord->branch = "Ibadan";
      $Landlord->kin_name = "null";
      $Landlord->kin_phone = "null";
      $Landlord->kin_address = "Felele Area, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaja";
      $Landlord->name = "Aramid Store";
      $Landlord->phone = "08033263294";
      $Landlord->email = "remi.olofa@remiolofa.com";
      $Landlord->address_office = "No 8 Robo Corner, Agbeni Ibadan";
      $Landlord->address_residence = "Oke Bola Shopping, Complex";
      $Landlord->bank_name = "null";
      $Landlord->account_name = "null";
      $Landlord->account_no = "null";
      $Landlord->branch = "null";
      $Landlord->kin_name = "Mr Remi Olofa";
      $Landlord->kin_phone = "08056242985";
      $Landlord->kin_address = "Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaja";
      $Landlord->name = "Modinat Mustapha";
      $Landlord->phone = "08034016829";
      $Landlord->email = "null";
      $Landlord->address_office = "null";
      $Landlord->address_residence = "null";
      $Landlord->bank_name = "First Bank";
      $Landlord->account_name = "Mustapha Modinat Oluwatosin";
      $Landlord->account_no = "3029232779";
      $Landlord->branch = "Dugbe";
      $Landlord->kin_name = "Omi Adio";
      $Landlord->kin_phone = "null";
      $Landlord->kin_address = "null";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaji";
      $Landlord->name = "Wasiu Sulaimon";
      $Landlord->phone = "08036643740";
      $Landlord->email = "null";
      $Landlord->address_office = "Adegoke Street, Orita";
      $Landlord->address_residence = "Orita Challenge, Ibadan";
      $Landlord->bank_name = "First Bank";
      $Landlord->account_name = "Wasgroup Enterprises";
      $Landlord->account_no = "1212010009488";
      $Landlord->branch = "Challenge";
      $Landlord->kin_name = "Mrs. Sulaimon";
      $Landlord->kin_phone = "08033603775";
      $Landlord->kin_address = "Orita Challenge, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaja";
      $Landlord->name = "Nimota Mustapha";
      $Landlord->phone = "07055983014";
      $Landlord->email = "sholathomas@att.net";
      $Landlord->address_office = "Orita Challenge";
      $Landlord->address_residence = "Challenge Ibadan.";
      $Landlord->bank_name = "null";
      $Landlord->account_name = "null";
      $Landlord->account_no = "null";
      $Landlord->branch = "null";
      $Landlord->kin_name = "Shola Thomas";
      $Landlord->kin_phone = "08089053244";
      $Landlord->kin_address = "London";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaji";
      $Landlord->name = "K.S.O Are";
      $Landlord->phone = "08033480294";
      $Landlord->email = "null";
      $Landlord->address_office = "Oke Are";
      $Landlord->address_residence = "Oke Are";
      $Landlord->bank_name = "Sterling Bank";
      $Landlord->account_name = "Estate of Alhaji K.S.O Are";
      $Landlord->account_no = "0013670026";
      $Landlord->branch = "Ibadan";
      $Landlord->kin_name = "Mojeed Are";
      $Landlord->kin_phone = "null";
      $Landlord->kin_address = "Akobo, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mr";
      $Landlord->name = "Kayode Olugbenga";
      $Landlord->phone = "08033088116";
      $Landlord->email = "null";
      $Landlord->address_office = "Oye Brothers, OYSSIC Complex, Iyaganku Ibadan";
      $Landlord->address_residence = "Kabiru Ajao Street, Powerline Ajadi Ologuneru, Ibadan";
      $Landlord->bank_name = "First Bank Plc";
      $Landlord->account_name = "Olugbenga Olukayode";
      $Landlord->account_no = "3040336056";
      $Landlord->branch = "Dugbe";
      $Landlord->kin_name = "Kayode";
      $Landlord->kin_phone = "08033023750";
      $Landlord->kin_address = "Kabiru Ajao Street, Powerline Ajadi Ologuneru, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaji";
      $Landlord->name = "Amusa Adedokun Olofa";
      $Landlord->phone = "080595228931";
      $Landlord->email = "null";
      $Landlord->address_office = "Oke Odo, Ibadan";
      $Landlord->address_residence = "Oke Odo, Ibadan";
      $Landlord->bank_name = "null";
      $Landlord->account_name = "null";
      $Landlord->account_no = "null";
      $Landlord->branch = "null";
      $Landlord->kin_name = "Mrs. Ayoola";
      $Landlord->kin_phone = "080595228931";
      $Landlord->kin_address = "Odo Ona, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mr";
      $Landlord->name = "Moruff Kunle Kolapo & Others";
      $Landlord->phone = "08033195108";
      $Landlord->email = "null";
      $Landlord->address_office = "Ogbomosho South L.G";
      $Landlord->address_residence = "Bashorun";
      $Landlord->bank_name = "UBA";
      $Landlord->account_name = "Ayeni Taiwo";
      $Landlord->account_no = "2012899201";
      $Landlord->branch = "Osogbo";
      $Landlord->kin_name = "Laide Kolapo";
      $Landlord->kin_phone = "08032099237";
      $Landlord->kin_address = "Eleyele";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mr";
      $Landlord->name = "O. Adeagbo";
      $Landlord->phone = "08038304839";
      $Landlord->email = "null";
      $Landlord->address_office = "Ibadan";
      $Landlord->address_residence = "Osungbade, Ibadan";
      $Landlord->bank_name = "null";
      $Landlord->account_name = "null";
      $Landlord->account_no = "null";
      $Landlord->branch = "null";
      $Landlord->kin_name = "Mrs. Adeagbo";
      $Landlord->kin_phone = "08032579433";
      $Landlord->kin_address = "Osungbade, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mr";
      $Landlord->name = "Samuel Olanrewaju";
      $Landlord->phone = "+2407319887";
      $Landlord->email = "null";
      $Landlord->address_office = "London";
      $Landlord->address_residence = "London";
      $Landlord->bank_name = "United Bank for Africa";
      $Landlord->account_name = "Olanrewaju Samuel Folorunsho";
      $Landlord->account_no = "1015633236";
      $Landlord->branch = "Dugbe";
      $Landlord->kin_name = "Segun Awolola";
      $Landlord->kin_phone = "08054226794";
      $Landlord->kin_address = "Mokola Area, Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Mr";
      $Landlord->name = "Adelokun Salami";
      $Landlord->phone = "08053153900";
      $Landlord->email = "null";
      $Landlord->address_office = "Agbeni Market";
      $Landlord->address_residence = "Beyerunka, Ibadan";
      $Landlord->bank_name = "null";
      $Landlord->account_name = "null";
      $Landlord->account_no = "null";
      $Landlord->branch = "null";
      $Landlord->kin_name = "Muibat Salam";
      $Landlord->kin_phone = "08053153900";
      $Landlord->kin_address = "Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();

      $Landlord = new Landlord();
      $Landlord->title = "Alhaja";
      $Landlord->name = "R. A Badaru (Liberty)";
      $Landlord->phone = "07061311542";
      $Landlord->email = "null";
      $Landlord->address_office = "Ibadan";
      $Landlord->address_residence = "Behind Ibadan Grammar School Molete, Ibadan";
      $Landlord->bank_name = "United Bank for Africa";
      $Landlord->account_name = "Mutiat Adebola Olowo";
      $Landlord->account_no = "2018671001";
      $Landlord->branch = "Dugbe";
      $Landlord->kin_name = "Alhaja Mutiat Olowo";
      $Landlord->kin_phone = "07061311542";
      $Landlord->kin_address = "Behind Ibadan Grammar School, Molete Ibadan";
      $Landlord->officer_id = 5;
      $Landlord->account = 0.00;
      $Landlord->created_by_id = 1;
      $Landlord->save();
    }
}
