<?php

use App\Property;
use Illuminate\Database\Seeder;

class PropertiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     public function run()
     {
      $properties = [[
            "id" =>  12,
            "landlord_id" =>  10,
            "created_at" =>  "2015-07-23 11:38:01",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-01-27 14:01:20",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "New Property",
            "name" =>  "Twin Bungalow at Ashi, Old Bodija, Ibadan of Dr. Popoola Tokede",
            "state" =>  "OYO",
            "bank_name" =>  "",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  "2016-01-27 14:50:14",
            "officer_id" =>  1
        ],
        [
            "id" =>  17,
            "landlord_id" =>  19,
            "created_at" =>  "2016-01-11 15:34:03",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-01-28 11:47:09",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "New Property",
            "name" =>  "Tenement House of Dr. Kolawole at Oke Ado Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "Yes",
            "dormant_date" =>  "2016-01-28 12:47:09",
            "officer_id" =>  1
        ],
        [
            "id" =>  18,
            "landlord_id" =>  19,
            "created_at" =>  "2016-01-21 11:05:22",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-01-27 13:09:47",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  5,
            "is_new" =>  "New Property",
            "name" =>  "Detached Property of Dr. Clement Kolawole at Odo Ona Elewure",
            "state" =>  "OYO",
            "bank_name" =>  "Fidelity Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  19,
            "landlord_id" =>  1,
            "created_at" =>  "2016-01-29 13:21:27",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-01-29 13:21:27",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  8,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "OYO STATE SMALL SCALE INDUSTRY COMPLEX",
            "state" =>  "OYO",
            "bank_name" =>  "ECO BANK NIG. PLC",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  20,
            "landlord_id" =>  3,
            "created_at" =>  "2016-02-02 12:34:43",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-16 11:41:02",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Arijo shopping complex at Agbeni, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "First City Monument Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  21,
            "landlord_id" =>  4,
            "created_at" =>  "2016-02-03 08:48:39",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-03 08:48:39",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2no shops at New Gbagi Market, Ibadan of Alhaji Ibrahim Oyeleye",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  22,
            "landlord_id" =>  1,
            "created_at" =>  "2016-02-04 10:17:16",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-04 10:17:16",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  8,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "OYSSIC",
            "state" =>  "OYO",
            "bank_name" =>  "ECO BANK NIG. PLC",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  23,
            "landlord_id" =>  36,
            "created_at" =>  "2016-02-19 11:56:57",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-19 11:56:57",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement building of Alhaji Tairu Akinade",
            "state" =>  "OYO",
            "bank_name" =>  "Skye  Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  24,
            "landlord_id" =>  36,
            "created_at" =>  "2016-02-25 08:40:51",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 08:40:51",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement Property located at Molade Area, Iwo Road, Ibadan.",
            "state" =>  "OYO",
            "bank_name" =>  "Skye  Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  25,
            "landlord_id" =>  31,
            "created_at" =>  "2016-02-25 08:46:33",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 08:46:33",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement Property located at Molade Area, Ibadan.",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  26,
            "landlord_id" =>  44,
            "created_at" =>  "2016-02-25 08:55:02",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 08:55:02",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement Property located at Ehin Grammar, Molete, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Skye Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  27,
            "landlord_id" =>  29,
            "created_at" =>  "2016-02-25 08:58:53",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 11:16:10",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Shops at Olunde Area, Ibadan.",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  28,
            "landlord_id" =>  4,
            "created_at" =>  "2016-02-25 09:02:09",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:02:09",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Shops at New Gbagi, Market, Ibadan ",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  29,
            "landlord_id" =>  11,
            "created_at" =>  "2016-02-25 09:04:24",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:04:24",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Adegoke Street, Orita Challenge, Ibadan.",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  30,
            "landlord_id" =>  12,
            "created_at" =>  "2016-02-25 09:06:52",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:06:52",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Orita Challenge, Ibadan.",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  31,
            "landlord_id" =>  14,
            "created_at" =>  "2016-02-25 09:10:18",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:10:18",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Lebanon Street, Old Gbagi Market, Ibadan.",
            "state" =>  "OYO",
            "bank_name" =>  "Sterling Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  32,
            "landlord_id" =>  25,
            "created_at" =>  "2016-02-25 09:13:09",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:13:09",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "New Gbagi Market, Ibadan ",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  33,
            "landlord_id" =>  2,
            "created_at" =>  "2016-02-25 09:27:06",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:27:06",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Felele Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Union Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  34,
            "landlord_id" =>  8,
            "created_at" =>  "2016-02-25 09:30:18",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:30:18",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Fanawole Area, Apete, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "GTB",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  35,
            "landlord_id" =>  35,
            "created_at" =>  "2016-02-25 09:55:23",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:55:23",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Ire Akari Estate, Soka",
            "state" =>  "OYO",
            "bank_name" =>  "GTBank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  36,
            "landlord_id" =>  43,
            "created_at" =>  "2016-02-25 09:59:00",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 09:59:00",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  2,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Alarere Area, Iwo Road, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  37,
            "landlord_id" =>  8,
            "created_at" =>  "2016-02-25 10:01:20",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 10:01:20",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  6,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Felele Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "GTB",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  38,
            "landlord_id" =>  17,
            "created_at" =>  "2016-02-25 10:04:49",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 10:04:49",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Old Gbagi, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  39,
            "landlord_id" =>  38,
            "created_at" =>  "2016-02-25 10:13:22",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 10:13:22",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Olorunsogo Akanran Road, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  40,
            "landlord_id" =>  39,
            "created_at" =>  "2016-02-25 10:35:48",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-25 10:35:48",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Olorunsogo Akanran Road, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  41,
            "landlord_id" =>  41,
            "created_at" =>  "2016-02-26 09:01:12",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-02-26 09:01:12",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Block of two flat at Olorunlogbon Area, Ayegun",
            "state" =>  "OYO",
            "bank_name" =>  "Skye Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  42,
            "landlord_id" =>  54,
            "created_at" =>  "2016-03-02 09:52:59",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-02 09:52:59",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 12 rooms of Moruf, Kunle Kolapo and Others at Sapati Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  43,
            "landlord_id" =>  17,
            "created_at" =>  "2016-03-02 14:59:12",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-22 11:19:15",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 12 rooms at Benjamin Area, Eleyele, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  44,
            "landlord_id" =>  26,
            "created_at" =>  "2016-03-08 10:08:48",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-08 10:08:48",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "A Block of twin bungalow Odo Oba Area belong to Alh. Saidat B. Yusuf ",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  45,
            "landlord_id" =>  10,
            "created_at" =>  "2016-03-08 10:13:57",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-08 10:13:57",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "shops at Omi Adio of Alhaja Modinat Mustapha",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  46,
            "landlord_id" =>  57,
            "created_at" =>  "2016-03-11 15:11:37",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-29 14:03:10",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "A wing of 4 rooms at Anlugbua, 3 bedroom at Apata and 3 bedroom at Akobo Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Zenith Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  47,
            "landlord_id" =>  6,
            "created_at" =>  "2016-03-11 15:14:39",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-11 15:14:39",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 8 rooms at Oke Ado of Mr. Akorede Adisa",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  48,
            "landlord_id" =>  9,
            "created_at" =>  "2016-03-11 15:16:09",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-11 15:16:09",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "A shop at Oke Bola of Aramid Stores",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  49,
            "landlord_id" =>  13,
            "created_at" =>  "2016-03-11 15:18:37",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-11 15:18:37",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "An office space at Orita Challenge Ibadan of Alhaja Nimota Mustapha",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  50,
            "landlord_id" =>  67,
            "created_at" =>  "2016-03-15 09:44:28",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-15 09:44:28",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property at Odo - Oba Elere",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  51,
            "landlord_id" =>  69,
            "created_at" =>  "2016-03-15 10:01:37",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-15 10:01:37",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "middle shop at Salami Adelokun Property at Beyerunka",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  52,
            "landlord_id" =>  16,
            "created_at" =>  "2016-03-15 10:45:48",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-15 10:45:48",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of Alh (late) Amusa Adedokun Olofa at Oke Odo",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  53,
            "landlord_id" =>  70,
            "created_at" =>  "2016-03-17 15:24:48",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-17 15:24:48",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "a block of twin flat property Alhaja Adenike Olofa ",
            "state" =>  "OYO",
            "bank_name" =>  "Damond Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  54,
            "landlord_id" =>  30,
            "created_at" =>  "2016-03-17 15:44:03",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-17 15:44:03",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "A block of twin flat , Alhaji Abass Adeyemo property Boluwaji Area",
            "state" =>  "OYO",
            "bank_name" =>  "GTBank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  55,
            "landlord_id" =>  32,
            "created_at" =>  "2016-03-17 16:18:53",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-17 16:18:53",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "twin bungalow at osungbade Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  56,
            "landlord_id" =>  18,
            "created_at" =>  "2016-03-17 16:34:41",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-17 16:34:41",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "four flat at Adeyemo Area",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  57,
            "landlord_id" =>  21,
            "created_at" =>  "2016-03-18 15:29:11",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-18 15:29:11",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 24 rooms at Liberty Road of Alhaja R. A. Badaru",
            "state" =>  "OYO",
            "bank_name" =>  "United Bank for Africa",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  58,
            "landlord_id" =>  48,
            "created_at" =>  "2016-03-18 15:32:21",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-03-18 15:32:21",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 20 rooms at Yemetu of Alhaja M.A Kolapo",
            "state" =>  "OYO",
            "bank_name" =>  "Eco Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  59,
            "landlord_id" =>  71,
            "created_at" =>  "2016-04-01 11:43:41",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-01 11:43:41",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Flat of 3-bedroom each at Odo Oba, Property of B.K Ayinde",
            "state" =>  "OYO",
            "bank_name" =>  "GTB",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  60,
            "landlord_id" =>  51,
            "created_at" =>  "2016-04-13 13:33:24",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 13:33:24",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 20 rooms at Agbokojo,Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Skye Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  61,
            "landlord_id" =>  24,
            "created_at" =>  "2016-04-13 13:38:44",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 13:38:44",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 24 rooms and shops at Abayomi, iwo Road of S. O Balogun",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  62,
            "landlord_id" =>  30,
            "created_at" =>  "2016-04-13 13:42:59",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 13:42:59",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  4,
            "is_new" =>  "Pre-Occupied",
            "name" =>  " 2 blocks of six flat each at Fodasic Area, Ibadan of Alhaji Abass Adeyemo",
            "state" =>  "OYO",
            "bank_name" =>  "GTBank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  63,
            "landlord_id" =>  52,
            "created_at" =>  "2016-04-13 13:52:19",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 13:52:19",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "20 no shops at Labaowo, ibadan of Alhaji Remi Olofa",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  64,
            "landlord_id" =>  13,
            "created_at" =>  "2016-04-13 13:57:30",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 13:57:30",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 building of 2 floors for office space at idi odo of Alhaja Nimota Mustapha",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  65,
            "landlord_id" =>  53,
            "created_at" =>  "2016-04-13 14:00:27",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 14:00:27",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "20 no Shops at Oke Seni Ibadan of Alhaji Aderemi Olofa",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  66,
            "landlord_id" =>  62,
            "created_at" =>  "2016-04-13 14:06:48",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 14:06:48",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Block of four flats at Bogije, Lagos of Alhaji Lateef Adebayo Yusuf",
            "state" =>  "LAGOS",
            "bank_name" =>  "First Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  67,
            "landlord_id" =>  28,
            "created_at" =>  "2016-04-13 14:51:58",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-13 14:51:58",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 no Bungalow at No 41\/43 Adeyi Avenue Old Bodija Ibadan of Chief (Late) L. F Igbosanya",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  68,
            "landlord_id" =>  72,
            "created_at" =>  "2016-04-14 15:08:01",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-14 15:08:01",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Row of Shops at M.A. Kolapo at Wondo Corner, Old Gbagi  ",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  69,
            "landlord_id" =>  73,
            "created_at" =>  "2016-04-14 15:37:56",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-14 15:37:56",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Right side shop at Aboaba trustee property at Olorunsogo",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  70,
            "landlord_id" =>  36,
            "created_at" =>  "2016-04-14 15:53:37",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-14 15:53:37",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement building Alhaji Tairu Akinade property at Molade Area",
            "state" =>  "OYO",
            "bank_name" =>  "Skye  Bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  71,
            "landlord_id" =>  16,
            "created_at" =>  "2016-04-19 14:18:20",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 14:18:20",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 No shops at Alesinloye Market Ibadan of Alhaji Amusa Adedokun Olofa",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  72,
            "landlord_id" =>  37,
            "created_at" =>  "2016-04-19 14:20:48",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 14:20:48",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property and shops at Mokola Ibadan of Late KSO Aree",
            "state" =>  "OYO",
            "bank_name" =>  "Sterling Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  73,
            "landlord_id" =>  42,
            "created_at" =>  "2016-04-19 14:22:35",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 14:22:35",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  5,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Detached house at 136, Sinari Daranijo Street, V.I of Dr. J.A Williams",
            "state" =>  "LAGOS",
            "bank_name" =>  "First Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  75,
            "landlord_id" =>  15,
            "created_at" =>  "2016-04-19 14:43:26",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 14:43:26",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 Blocks of 2 flats at Akorede Area, Sango Ibadan of Mr. Kayode Olugbenga",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  76,
            "landlord_id" =>  19,
            "created_at" =>  "2016-04-19 14:46:22",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 14:46:22",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  5,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "A detached house of 4 bedroom at Apata, Ibadan of Mr. Samuel Olanrewaju",
            "state" =>  "OYO",
            "bank_name" =>  "United Bank for Africa",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  77,
            "landlord_id" =>  45,
            "created_at" =>  "2016-04-19 14:50:23",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 14:50:23",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  2,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 storey of six flats at Majerita Area of Mr. Kehinde Adeleye Anthony",
            "state" =>  "OYO",
            "bank_name" =>  "Diamond Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  78,
            "landlord_id" =>  46,
            "created_at" =>  "2016-04-19 14:52:23",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 14:52:23",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Block of 4 flats at Total Filling Station Area Ijebu Igbo of Anthony Kehinde Adeleye",
            "state" =>  "OGUN",
            "bank_name" =>  "Diamond Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  79,
            "landlord_id" =>  45,
            "created_at" =>  "2016-04-19 14:55:16",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 14:55:16",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 No Blocks of 4 flats each beside Blue View Hotel of Mr. Kehinde Adeleye Anthony",
            "state" =>  "OYO",
            "bank_name" =>  "Diamond Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  80,
            "landlord_id" =>  5,
            "created_at" =>  "2016-04-19 15:00:40",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:00:40",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 8 rooms at oke itunu, ibadan of Mrs. Modupe Okoaye",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  81,
            "landlord_id" =>  22,
            "created_at" =>  "2016-04-19 15:02:49",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:02:49",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  " 3 No office space at Ososami Area Ibadan of Mrs. N. A. Adesanya",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  82,
            "landlord_id" =>  63,
            "created_at" =>  "2016-04-19 15:04:41",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:04:41",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Block of 4 flat at Apata, Ibadan of Mr. T.O Akinkunmi",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  83,
            "landlord_id" =>  59,
            "created_at" =>  "2016-04-19 15:07:16",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:07:16",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "17 No shops at Ifeleye market, Ibadan of Mr. Adejare Adedoja",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  84,
            "landlord_id" =>  55,
            "created_at" =>  "2016-04-19 15:08:48",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:08:48",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Shops at Oja Oba Ibadan of Mr. Adejare Adedoja",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  85,
            "landlord_id" =>  17,
            "created_at" =>  "2016-04-19 15:11:43",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:11:43",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property and Shops Opposite Onado Filling Station Eleyeye Ibadan of Kolapo Moruf & Others",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  86,
            "landlord_id" =>  50,
            "created_at" =>  "2016-04-19 15:13:44",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:13:44",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "office space and shops at Samonda Area, Ibadan of Mrs. G. O. Ogunmola",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  87,
            "landlord_id" =>  47,
            "created_at" =>  "2016-04-19 15:19:56",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:19:56",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Block of 4 flats at Jankata Area, Apata Ibadan of Mrs. Abiola Aramide",
            "state" =>  "OYO",
            "bank_name" =>  "Zenith Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  88,
            "landlord_id" =>  49,
            "created_at" =>  "2016-04-19 15:22:14",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:22:14",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Block of 4 flats at Bashorun Area, Ibadan of Mrs. M. O. Adeagbo",
            "state" =>  "OYO",
            "bank_name" =>  "First Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  89,
            "landlord_id" =>  56,
            "created_at" =>  "2016-04-19 15:24:12",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:24:12",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 20 rooms at Ososami, Ibadan of Mrs. J. I Adegbuyi",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  90,
            "landlord_id" =>  61,
            "created_at" =>  "2016-04-19 15:26:18",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:26:18",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 12 rooms at Elekuro Ibadan of Mrs. D. O. Opasina",
            "state" =>  "OYO",
            "bank_name" =>  "United Bank for Africa",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  91,
            "landlord_id" =>  13,
            "created_at" =>  "2016-04-19 15:29:41",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-19 15:29:41",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 No properties for office use at Idi odo Challenge, Ibadan of Alhaja Nimota Mustapha",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  92,
            "landlord_id" =>  74,
            "created_at" =>  "2016-04-22 10:05:13",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-22 10:05:13",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 3 wings and shops at Sapati Ibadan of Alhaja Mulikat Kolapo",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  93,
            "landlord_id" =>  17,
            "created_at" =>  "2016-04-22 11:21:42",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-22 11:21:42",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 12 rooms at Benjamin Area, Eleyele, Ibadan of Moruf Kolapo & Others",
            "state" =>  "OYO",
            "bank_name" =>  "UBA",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  94,
            "landlord_id" =>  75,
            "created_at" =>  "2016-04-28 15:01:34",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-28 15:01:34",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 storey building of office space at Oje Ibadan of Alhaji Bello Adekunle",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  95,
            "landlord_id" =>  76,
            "created_at" =>  "2016-04-28 15:23:29",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-28 15:23:29",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  5,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Bungalow of 4 bedroom at Arowolo Area, Odo Ona Elewe of Mr. A. O. Aderionkun",
            "state" =>  "OYO",
            "bank_name" =>  "Stanbic Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  96,
            "landlord_id" =>  78,
            "created_at" =>  "2016-04-29 14:31:14",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-29 14:31:14",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "3 bedroom bungalow at Ila Orangun of Mr Samuel Olanrewaju",
            "state" =>  "OSUN",
            "bank_name" =>  "United Bank for Africa",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  97,
            "landlord_id" =>  7,
            "created_at" =>  "2016-04-29 14:41:56",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-04-29 14:41:56",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 8 rooms at Oke Itunu of A.O Aderionkun",
            "state" =>  "OYO",
            "bank_name" =>  "Stanbic Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  98,
            "landlord_id" =>  13,
            "created_at" =>  "2016-05-03 14:20:29",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-05-03 14:20:29",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 blocks consist of 6 No office space and 1 shop",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  99,
            "landlord_id" =>  5,
            "created_at" =>  "2016-05-03 15:18:45",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-05-03 15:18:45",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 8 rooms at Oke Itunu of Mrs. Modupe Okoaye",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  100,
            "landlord_id" =>  79,
            "created_at" =>  "2016-05-03 16:04:18",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-05-03 16:04:18",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  5,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "3 bedroom flat at Oluyole Estate of Mr. Micheal Akande",
            "state" =>  "OYO",
            "bank_name" =>  "United Bank for Africa",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  101,
            "landlord_id" =>  80,
            "created_at" =>  "2016-05-05 14:37:21",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-05-05 14:37:21",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "A block of 4 flats at Oroki High School Area, Osogbo",
            "state" =>  "OSUN",
            "bank_name" =>  "Diamond Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  102,
            "landlord_id" =>  81,
            "created_at" =>  "2016-10-20 09:52:21",
            "created_by_id" =>  1,
            "updated_at" =>  "2016-10-20 09:52:21",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Shopping complex at Foko Junction Area,  Agbeni, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Skye Bank Plc",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  103,
            "landlord_id" =>  60,
            "created_at" =>  "2017-01-16 10:06:57",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-16 10:06:57",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "shopping complex at Agbeni Olora Compound",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  104,
            "landlord_id" =>  82,
            "created_at" =>  "2017-01-17 09:44:00",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-17 09:44:00",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "New Property",
            "name" =>  "Ile Titun, Near NIHORT, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  105,
            "landlord_id" =>  52,
            "created_at" =>  "2017-01-19 12:00:00",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-19 12:00:00",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Ajimajasan Building, Labaowo Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  106,
            "landlord_id" =>  55,
            "created_at" =>  "2017-01-19 15:56:50",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-19 15:56:50",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Shopping complex at Oja Oba, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  107,
            "landlord_id" =>  84,
            "created_at" =>  "2017-01-27 10:34:25",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-27 10:34:25",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Felele Extension",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  108,
            "landlord_id" =>  85,
            "created_at" =>  "2017-01-27 11:34:03",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-27 11:34:03",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Shopping Complex at Agbaje Market, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  109,
            "landlord_id" =>  86,
            "created_at" =>  "2017-01-30 09:19:10",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-30 09:19:10",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "shopping complex at labaowo market (Ajimajasan Building)",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  110,
            "landlord_id" =>  87,
            "created_at" =>  "2017-01-30 10:35:20",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-30 10:35:20",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Ekotedo Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  111,
            "landlord_id" =>  87,
            "created_at" =>  "2017-01-30 11:03:12",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-01-30 11:03:12",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property at Ekotedo Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  112,
            "landlord_id" =>  88,
            "created_at" =>  "2017-02-09 09:46:41",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-09 09:46:41",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Commercial property at No 29, Lebanon Street, Old Gbagi, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  113,
            "landlord_id" =>  83,
            "created_at" =>  "2017-02-10 10:28:54",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-10 10:28:54",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Shopping complex of 17 shops at Ifeleye, ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  114,
            "landlord_id" =>  89,
            "created_at" =>  "2017-02-16 15:50:53",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-16 15:50:53",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "ALAGBO AREA, OLODO GARAGE, IWO ROAD, IBADAN",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  115,
            "landlord_id" =>  90,
            "created_at" =>  "2017-02-16 16:22:36",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-16 16:22:36",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Komapayi Area, Olodo Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "STABIC IBTC",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  116,
            "landlord_id" =>  91,
            "created_at" =>  "2017-02-17 11:29:56",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-17 11:29:56",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "ROAD 1, NO 16, OLUKUNLE, OLODO AREA, IWO-ROAD, IBADAN",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  117,
            "landlord_id" =>  92,
            "created_at" =>  "2017-02-17 13:22:04",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-17 13:22:04",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "building of 8 rooms at Oki Area, Olodo for Alhaja Haleem Kudirat A",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  118,
            "landlord_id" =>  93,
            "created_at" =>  "2017-02-17 13:59:02",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-17 13:59:02",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property at Agbokojo Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  119,
            "landlord_id" =>  94,
            "created_at" =>  "2017-02-17 16:05:28",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-17 16:05:28",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "GALILI AREA, OLODO, IWO ROAD, IBADAN",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  120,
            "landlord_id" =>  95,
            "created_at" =>  "2017-02-17 16:36:22",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-17 16:36:22",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Oki Area, Alalubarika house, Iwo Road, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  121,
            "landlord_id" =>  96,
            "created_at" =>  "2017-02-20 09:10:43",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-20 09:10:43",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenament property on two floor,at olorunsogo area, Molete, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  122,
            "landlord_id" =>  3,
            "created_at" =>  "2017-02-27 12:44:03",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-02-27 12:44:03",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  9,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "shopping complex Opposite ogunpa river, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  123,
            "landlord_id" =>  97,
            "created_at" =>  "2017-03-06 16:39:57",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-03-06 16:39:57",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 16 rooms at Aba Pan, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  124,
            "landlord_id" =>  98,
            "created_at" =>  "2017-03-10 07:57:59",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-03-10 07:57:59",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 flats of 3 bedroom each (one up and down) and shops",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  125,
            "landlord_id" =>  99,
            "created_at" =>  "2017-03-20 13:35:23",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-03-20 13:35:23",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenement property of 16 rooms at Odo Oye, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  126,
            "landlord_id" =>  101,
            "created_at" =>  "2017-03-27 12:31:54",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-03-27 12:31:54",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "4 flats of 3bedroom each at Sanyo Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  127,
            "landlord_id" =>  102,
            "created_at" =>  "2017-04-11 12:05:44",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-04-11 12:05:44",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Taiwo Street, Sango Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  128,
            "landlord_id" =>  103,
            "created_at" =>  "2017-04-12 16:37:08",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-04-12 16:37:08",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "TENEMENT BUILDING OF EIGHT ROOM, ALALUBARIKA COMPOUND, OKI, OLODO,IBADAN",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  129,
            "landlord_id" =>  100,
            "created_at" =>  "2017-04-13 09:18:32",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-04-13 09:18:32",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  " Tenement property at Anlugbua, Apata & Akobo",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  130,
            "landlord_id" =>  104,
            "created_at" =>  "2017-04-13 12:33:52",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-04-13 12:33:52",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  5,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Detached bungalow of 2 bedroom at Oluyole Estate, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  131,
            "landlord_id" =>  105,
            "created_at" =>  "2017-05-11 12:30:55",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-05-11 12:30:55",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Tenament building of 16rooms at Iyemetu area, behind first bank",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  132,
            "landlord_id" =>  106,
            "created_at" =>  "2017-06-16 11:30:13",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-06-16 11:30:13",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Sharp Corner Area, Apata Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  133,
            "landlord_id" =>  107,
            "created_at" =>  "2017-08-17 14:47:30",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-08-17 14:47:30",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Shop No 97 at Adamasingba Shopping complex",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  134,
            "landlord_id" =>  108,
            "created_at" =>  "2017-08-29 15:20:23",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-08-29 15:20:23",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "twin bungalow of Mrs. Obiwale at Adetokun, Ologuneru ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  135,
            "landlord_id" =>  109,
            "created_at" =>  "2017-10-31 12:38:38",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-10-31 12:38:38",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "3 bedroom flat at Akobo",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  136,
            "landlord_id" =>  110,
            "created_at" =>  "2017-11-06 08:36:29",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-11-06 08:36:29",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "New Property",
            "name" =>  "BLOCK OF 3FLAT AT OGUNSOLA LAYOUT, OWOLEMI STREET, ODO - OBA",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  137,
            "landlord_id" =>  110,
            "created_at" =>  "2017-11-06 09:52:18",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-11-06 09:52:18",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "New Property",
            "name" =>  "Block of 2nos 3-bedroom flat at Owolemi Street, Odo Oba,ppty of Mr. Lanipekun Moses Olabamiji ",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  138,
            "landlord_id" =>  111,
            "created_at" =>  "2017-11-16 14:06:19",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-11-16 14:06:19",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Alao Akala Estate, Oke Ibadan Estate, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "sterling bank",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  139,
            "landlord_id" =>  112,
            "created_at" =>  "2017-11-20 09:32:32",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-11-20 09:32:32",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  11,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Commercial Property at Idi Odo comprising of 2 No Buildings",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  140,
            "landlord_id" =>  113,
            "created_at" =>  "2017-12-05 11:10:38",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-12-05 11:10:38",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "New Property",
            "name" =>  "No 2, Dimeji Lawal Street, Felele, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  141,
            "landlord_id" =>  113,
            "created_at" =>  "2017-12-05 11:16:49",
            "created_by_id" =>  1,
            "updated_at" =>  "2017-12-05 11:16:49",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "New Property",
            "name" =>  "No 2, Dimeji Lawal Street, Felele Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  142,
            "landlord_id" =>  72,
            "created_at" =>  "2018-01-10 14:42:39",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-01-10 14:42:39",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  10,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Agodi and Sango",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  143,
            "landlord_id" =>  114,
            "created_at" =>  "2018-01-10 16:25:07",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-01-10 16:25:07",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "A Story Building with Boys Quarters, Yerokun Street, Academy Area, Ibadan  ",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  144,
            "landlord_id" =>  115,
            "created_at" =>  "2018-01-11 14:13:57",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-01-11 14:13:57",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Yerokun Street, Academy Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  145,
            "landlord_id" =>  115,
            "created_at" =>  "2018-01-11 14:50:06",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-01-11 14:50:06",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Yerokun Street, Academy Area, Ibadan (House 2)",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  146,
            "landlord_id" =>  115,
            "created_at" =>  "2018-01-11 15:21:54",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-01-11 15:21:54",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "2 story Building at Yerokun Street, Academy Area, Ibadan. (House 2)",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  147,
            "landlord_id" =>  116,
            "created_at" =>  "2018-01-26 10:22:00",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-01-26 10:22:00",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "oloronbo",
            "state" =>  "ONDO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  148,
            "landlord_id" =>  117,
            "created_at" =>  "2018-02-12 09:12:12",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-02-12 09:12:12",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Boluwaji Area Sanyo Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  149,
            "landlord_id" =>  118,
            "created_at" =>  "2018-03-12 15:23:49",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-03-12 15:23:49",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  2,
            "is_new" =>  "New Property",
            "name" =>  "Adeleye Crescent, Elebu Area",
            "state" =>  "OYO",
            "bank_name" =>  "ACCESS BANK",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  150,
            "landlord_id" =>  119,
            "created_at" =>  "2018-04-10 09:54:28",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-04-10 09:54:28",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  5,
            "is_new" =>  "New Property",
            "name" =>  "Plot 6, Block 39, Kolapo Ishola GRA, Akobo, Iwo Road Lagalu, ",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  151,
            "landlord_id" =>  120,
            "created_at" =>  "2018-04-30 08:18:36",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-04-30 08:18:36",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Adabale compound, Iyemetu, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  152,
            "landlord_id" =>  121,
            "created_at" =>  "2018-05-07 13:12:05",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-05-07 13:12:05",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "New Property",
            "name" =>  "23, Onikeke, Ayegoro Junction, Opposite Kolapo Ishola Estate, Akobo, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  153,
            "landlord_id" =>  121,
            "created_at" =>  "2018-05-18 09:36:50",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-05-18 09:36:50",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  12,
            "is_new" =>  "New Property",
            "name" =>  "Block of three bedroom flat at 23, Onikeke Ayegoro junction, opposite Kolapo Ishola Estate, Akobo, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  154,
            "landlord_id" =>  122,
            "created_at" =>  "2018-09-17 12:32:43",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-09-17 12:32:43",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  8,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "A block of four flat with boys quareters",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  155,
            "landlord_id" =>  122,
            "created_at" =>  "2018-09-17 13:14:09",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-09-17 13:14:09",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  8,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Block of 4 bedroom flats with Boysquarters at Onigbagbo, Iwo Road, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  156,
            "landlord_id" =>  123,
            "created_at" =>  "2018-09-17 14:33:44",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-09-17 14:33:44",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  2,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "Block of 6 flat with boys quarter at Ogunsola Street, Apata Area, Ibadan ",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  157,
            "landlord_id" =>  124,
            "created_at" =>  "2018-10-02 16:31:26",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-10-02 16:31:26",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  8,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "67 Owolabi Street, off Ago Palace Way, Okota Lagos",
            "state" =>  "LAGOS",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  158,
            "landlord_id" =>  125,
            "created_at" =>  "2018-10-03 09:57:22",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-10-03 09:57:22",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  2,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "15 Shatola Street, Ajeigbe Area, Off Ring Road, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  159,
            "landlord_id" =>  126,
            "created_at" =>  "2018-10-12 09:30:29",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-10-12 09:30:29",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "ODO-YE, SAPATI AREA",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  160,
            "landlord_id" =>  1,
            "created_at" =>  "2018-11-26 11:29:36",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-11-26 11:29:36",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  8,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "FORMER NTC ROAD IYAGANKU IBADAN",
            "state" =>  "OYO",
            "bank_name" =>  "ECO BANK NIG. PLC",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  161,
            "landlord_id" =>  1,
            "created_at" =>  "2018-11-26 11:33:45",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-11-26 11:33:45",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  8,
            "is_new" =>  "New Property",
            "name" =>  "FORMER NTC ROAD IYAGANKU IBADAN",
            "state" =>  "OYO",
            "bank_name" =>  "ECO BANK NIG. PLC",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  162,
            "landlord_id" =>  1,
            "created_at" =>  "2018-11-26 11:42:07",
            "created_by_id" =>  1,
            "updated_at" =>  "2018-11-26 11:42:07",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  8,
            "is_new" =>  "New Property",
            "name" =>  "FORMER NTC ROAD IYAGANKU",
            "state" =>  "OYO",
            "bank_name" =>  "ECO BANK NIG. PLC",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  163,
            "landlord_id" =>  127,
            "created_at" =>  "2019-01-25 13:22:36",
            "created_by_id" =>  1,
            "updated_at" =>  "2019-01-25 13:22:36",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "New Property",
            "name" =>  "Araromi Estate Elebu Area Ibadan ",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  164,
            "landlord_id" =>  127,
            "created_at" =>  "2019-01-25 13:31:20",
            "created_by_id" =>  1,
            "updated_at" =>  "2019-01-25 13:31:20",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "New Property",
            "name" =>  "Araromi Estate Elebu Area Oluyole Extension Ibada",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "Yes",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  165,
            "landlord_id" =>  127,
            "created_at" =>  "2019-01-28 09:06:53",
            "created_by_id" =>  1,
            "updated_at" =>  "2019-01-28 09:06:53",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  1,
            "is_new" =>  "New Property",
            "name" =>  "Araromi Estate, Elebu Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  166,
            "landlord_id" =>  128,
            "created_at" =>  "2019-02-07 11:01:45",
            "created_by_id" =>  1,
            "updated_at" =>  "2019-02-07 11:01:45",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  7,
            "is_new" =>  "Pre-Occupied",
            "name" =>  "20, Dumoye Street, Benjamin Street, Eleyele, Area, Ibadan",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ],
        [
            "id" =>  167,
            "landlord_id" =>  129,
            "created_at" =>  "2019-04-15 09:54:20",
            "created_by_id" =>  1,
            "updated_at" =>  "2019-04-15 09:54:20",
            "updated_by_id" =>  null,
            "deleted_at" => null,
            "property_type_id" =>  3,
            "is_new" =>  "New Property",
            "name" =>  "Ayegoro Area, New Garage",
            "state" =>  "OYO",
            "bank_name" =>  "Select One",
            "is_bank" =>  "No",
            "is_dormant" =>  "",
            "dormant_date" =>  null,
            "officer_id" =>  1
        ]];

        Property::insert($properties);
      
     }
}
